import { AtlasProfile } from "./atlasProfile";
import { Settings } from "./settings";
import { todayStamp } from "./daily";
import { readFile, writeFile, fileExists, ensureDir, join } from "./vault";
import { inTauri } from "./demoFs";
import { unfurl } from "./unfurl";
import { savePhotoFromImage } from "./photos";
import { aiStoryImage, proceduralStoryCover, GenImage } from "./imagegen";
import { getWeather, Weather } from "./weather";
import { researchTopic, researchLocalNews, BriefStory } from "./dailynews";
import { aiBriefLead } from "./assist";

/** The Daily Brief: a once-a-day, location-aware news + weather digest the user
 *  configures in Settings (topics + location). It is generated by web search,
 *  cached as JSON under `.atlas/briefs/<date>.json` (a draft — nothing is
 *  published), and typeset by DailyBriefView as a newspaper. */

export interface BriefItem extends BriefStory {
  image?: string;     // source og:image URL, a vault path, or a data URL
  imageAi?: boolean;  // painted by an image model, never presented as source photography
  imageGenerated?: boolean; // any generated fallback, including the offline procedural fallback
  time?: string;      // exact local time when a local item is time-sensitive
}
export interface BriefSection { title: string; items: BriefItem[]; }
export interface DailyBrief {
  date: string;          // YYYY-MM-DD (local = JST on the user's machine)
  name: string;          // masthead, from Settings
  generatedAt: string;   // ISO timestamp
  lead?: string;         // "bottom line up front" — the day's connecting signal
  weather: Weather | null;
  local: BriefSection | null;
  sections: BriefSection[];
  notes: string[];       // soft errors (e.g. "AI: web search not enabled")
}

const briefDir = (profile: AtlasProfile) => join(profile.root, ".atlas/briefs");
const briefPath = (profile: AtlasProfile, date: string) => join(briefDir(profile), `${date}.json`);
const msg = (e: unknown) => (e instanceof Error ? e.message : String(e));

/** Has today's brief already been fetched? (the once-a-day guard) */
export async function hasBriefToday(profile: AtlasProfile, date = todayStamp()): Promise<boolean> {
  return fileExists(briefPath(profile, date));
}

/** Read a stored brief (today's by default), or null. */
export async function loadBrief(profile: AtlasProfile, date = todayStamp()): Promise<DailyBrief | null> {
  try { return JSON.parse(await readFile(briefPath(profile, date))) as DailyBrief; }
  catch { return null; }
}

/** Topics the user typed, split, trimmed, de-duped, capped. */
function parseTopics(raw: string): string[] {
  const seen = new Set<string>();
  return raw.split(/[,\n;]+/).map((t) => t.trim()).filter((t) => {
    const k = t.toLowerCase();
    if (!t || seen.has(k)) return false;
    seen.add(k);
    return true;
  }).slice(0, 6);
}

/** A shared counter lets a producer opt into one AI attempt for every missing
 *  source image while keeping concurrent sections from exceeding that total. */
export interface StoryImageBudget { ai: number }

/** Bounded-concurrency map (keeps photo work from stampeding the network). */
async function mapPool<T, R>(items: T[], limit: number, fn: (item: T) => Promise<R>): Promise<R[]> {
  const out: R[] = new Array(items.length);
  let next = 0;
  await Promise.all(Array.from({ length: Math.min(limit, items.length) || 0 }, async () => {
    for (let i = next++; i < items.length; i = next++) out[i] = await fn(items[i]);
  }));
  return out;
}

/** Resolve a photo for a story: the article's own image first, else a generated
 *  illustration (AI in the app within budget, a procedural cover otherwise),
 *  always labeled by its actual origin so it cannot be mistaken for source photography. */
async function resolvePhoto(profile: AtlasProfile, settings: Settings, story: BriefStory, budget: StoryImageBudget): Promise<Pick<BriefItem, "image" | "imageAi" | "imageGenerated">> {
  try {
    const u = await unfurl(story.url);
    if (u.image && /^https?:\/\//.test(u.image)) return { image: u.image, imageAi: false, imageGenerated: false };
  } catch { /* no source image — fall through to a generated one */ }
  let gen: GenImage | null = null;
  let imageAi = false;
  const key = settings.openaiKey.trim();
  if (inTauri && key && budget.ai > 0) {
    budget.ai--;
    try { gen = await aiStoryImage(key, story.title, story.summary); imageAi = true; }
    catch { gen = null; } // rate-limited / failed → fall back, don't drop the card
  }
  if (!gen) gen = proceduralStoryCover(story.title);
  try {
    // A unique stem keeps two same-titled stories from racing onto the same file.
    const stem = `${story.title}-${crypto.randomUUID().slice(0, 8)}`;
    const stored = await savePhotoFromImage(profile, ".atlas/brief-assets", stem, { b64: gen.b64, mime: gen.mime, name: story.title });
    return { image: stored, imageAi, imageGenerated: true };
  } catch { return {}; }
}

export async function addStoryImages<T extends BriefStory>(
  profile: AtlasProfile,
  settings: Settings,
  stories: T[],
  budget: StoryImageBudget,
): Promise<(T & Pick<BriefItem, "image" | "imageAi" | "imageGenerated">)[]> {
  return mapPool(stories, 3, async (s) => ({ ...s, ...(await resolvePhoto(profile, settings, s, budget)) }));
}

/** Generate today's brief from the user's settings and cache it. Network-heavy
 *  (web search + photos); call once per day, in the background. */
export async function generateDailyBrief(
  profile: AtlasProfile, settings: Settings, opts: { onProgress?: (m: string) => void } = {},
): Promise<DailyBrief> {
  const date = todayStamp();
  const key = settings.openaiKey.trim();
  const topics = parseTopics(settings.briefTopics);
  const notes: string[] = [];

  opts.onProgress?.("Checking local weather…");
  const weather = settings.briefLocation.trim()
    ? await getWeather(settings.briefLocation).catch(() => null)
    : null;

  opts.onProgress?.("Searching today's news…");
  const localP: Promise<BriefStory[]> = settings.briefLocation.trim()
    ? researchLocalNews(key, settings.briefLocation).catch((e) => { notes.push(`Local news: ${msg(e)}`); return []; })
    : Promise.resolve([]);
  const topicP = topics.map((t) =>
    researchTopic(key, t).then((s) => ({ t, s })).catch((e) => { notes.push(`${t}: ${msg(e)}`); return { t, s: [] as BriefStory[] }; }));
  const [localStories, topicResults] = await Promise.all([localP, Promise.all(topicP)]);

  opts.onProgress?.("Finding photos…");
  const imageCount = localStories.length + topicResults.reduce((sum, result) => sum + result.s.length, 0);
  const budget: StoryImageBudget = { ai: imageCount };
  const local: BriefSection | null = localStories.length
    ? { title: `Local — ${settings.briefLocation.trim()}`, items: await addStoryImages(profile, settings, localStories, budget) }
    : null;
  const sections: BriefSection[] = [];
  for (const { t, s } of topicResults) {
    if (s.length) sections.push({ title: t, items: await addStoryImages(profile, settings, s, budget) });
  }

  if (!local && !sections.length && !weather) {
    notes.push("Nothing came back — check your OpenAI web-search access, topics, and location.");
  }

  // Bottom line up front: one signal connecting the day's headlines.
  let lead: string | undefined;
  const headlines = [
    ...(local?.items ?? []).map((i) => i.title),
    ...sections.flatMap((s) => s.items.map((i) => i.title)),
  ];
  if (inTauri && key && headlines.length >= 2) {
    opts.onProgress?.("Writing the bottom line…");
    try { lead = await aiBriefLead(key, headlines.slice(0, 16)); }
    catch { /* the lead is optional polish */ }
  }

  const brief: DailyBrief = {
    date,
    name: settings.briefName.trim() || "Daily Brief",
    generatedAt: new Date().toISOString(),
    lead,
    weather, local, sections, notes,
  };
  await ensureDir(briefDir(profile));
  await writeFile(briefPath(profile, date), JSON.stringify(brief, null, 2));
  return brief;
}
